name: argmap

channels:
  - nvidia
  - pytorch
  - conda-forge
#  - defaults

dependencies:
  # base
  - python>=3.11
  # - pytorch::pytorch-cuda
  # Pytorch version >= 2.3.0 to support numpy>=2
  # see https://github.com/pytorch/pytorch/issues/107302
  - pytorch::pytorch>=2.3.0
  - ipykernel
  - ipywidgets
  - python-dotenv
  - polars

  # topic modeling
  - spacy
  # - spacy-model-en_core_web_lg # get this from huggingface instead to avoid spacy downgrade
  - sentence-transformers
  - hvplot
  - nbformat
  # Commenting out datashader due to raising conflcits and apparently not being imported
  # explicitely in the current codebase. Raising issues with python 3.12 and mamba, s
  # - datashader
  - scikit-image
  - plotly>=5.19.0 # newer version needed for certain plots in bertopic
  # - seaborn
  # - matplotlib

  # language model
  - transformers
  - accelerate
  - optimum

  - pip
  - pip:
    - -e . # In stall local argmap package in editable mode
    - bertopic
    - guidance
    # AutoGPTQ is not supported on macOS
    # - https://github.com/AutoGPTQ/AutoGPTQ
    # The below link generates error, replacing by specific version
    # - https://huggingface.co/spacy/en_core_web_lg/resolve/main/en_core_web_lg-any-py3-none-any.whl
    - https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.8.0/en_core_web_lg-3.8.0-py3-none-any.whl

  # postgres support
  # - connectorx
  # - sqlalchemy
  # - psycopg2